blue_size: 1
orange_size: 0

rewards:
  ball_touch: 1
  distance_player_ball: 0.0025
  velocity_player_to_ball: 0.00125
  facing_ball: 0.000625
  velocity: 0.000625

state_mutator:
  _target_: env.state_mutators.airial_curriculum.AirialTraining
  blue_size: 1
  orange_size: 0
  ball_height: 1000

obs_builder:
  pos_frequencies: 6

timeout_seconds: 300
no_touch_timeout_seconds: 10
