defaults: 
  - base
  - env_config: 1on0
  - env_runners: sweaty

training: 
  gamma: 0.995
  lambda_: 0.95
  lr: 1e-5
  entropy_coeff: 0.001
  train_batch_size_per_learner: 8192
  num_epochs: 32
  minibatch_size: 1024
  shuffle_batch_per_epoch: True
