training:
  gamma: 0.995
  lambda_: 0.95
  lr: 1e-5
  entropy_coeff: 0.005
  train_batch_size_per_learner: 8192
  num_epochs: 32
  minibatch_size: 1024
  shuffle_batch_per_epoch: True
  use_kl_loss: false
  vf_loss_coeff: 0.5

rl_module_spec:
  # load_state_path: /home/denbuzz/src/denbot-rl/cool_checkpoints/ball_hunt/learner_group/learner/rl_module/denbot
  model_config:
    fcnet_hiddens: [1024, 1024]
    fcnet_activation: LeakyReLU
