defaults:
  - base

env_config:
  curriculum:
    tasks:
      - envs: [ball_hunt]
      - envs: [air_dribble]

algorithm:
  callbacks:
    episode_data:
      _target_: training.callbacks.EpisodeData
