defaults:
  - base

curriculum:
  - airial

algorithm:
  callbacks:
    episode_data:
      _target_: training.callbacks.EpisodeData
    airial_curriculum: 
      _target_: training.callbacks.AirialCurriculum
