defaults:
  - base

env_config:
  curriculum:
    tasks:
      # - envs: [speed_flip, speed_flip, ball_hunt]
      - envs: [wall_air_dribble, wall_air_dribble, field_air_dribble, field_air_dribble, shooting, speed_flip, ball_hunt]

algorithm:
  callbacks:
    episode_data:
      _target_: training.callbacks.EpisodeData
