boost_gather:

  state_mutator:
    _target_: env.state_mutators.boost_gather.BoostGather
    blue_size: 1
    orange_size: 0

  rewards:
    # ball_touch: 1
    boost_collect: 0.1
    full_boost: 1
    # distance_player_ball: 0.0025
    # facing_ball: 0.000625
    # velocity_player_to_ball: 0.00125
    velocity: 0.000625
    boost_amount: 0.00125

  termination_cond:
    _target_: env.terminal_condition.FullBoost

  truncation_cond:
    _target_: env.terminal_condition.AnyCondition
    conditions:
      - _target_: env.terminal_condition.TimeoutCondition
        timeout_seconds: 10
      # - _target_: env.terminal_condition.NoTouchTimeoutCondition
      #   timeout_seconds: 30
