speed_flip:

  state_mutator:
    _target_: env.state_mutators.ball_hunt.SpeedFlip

  rewards:
    ball_touch: 1
    boost_collect: 0.1
    full_boost: 0
    distance_player_ball: 0.000625
    distance_ball_goal: 0
    facing_ball: 0.00125
    velocity_player_to_ball: 0.005
    velocity: 0.00125
    boost_amount: 0.00125
    boost_proximity: 0.00125

  termination_cond:
    _target_: env.terminal_condition.BallTouchTermination

  truncation_cond:
    _target_: env.terminal_condition.AnyCondition
    conditions:
      - _target_: env.terminal_condition.TimeoutCondition
        timeout_seconds: 3
      - _target_: env.terminal_condition.NoFlip
        delay: 1.5
